### ISSUE TITLE
How to make release builds?

### ISSUE THREAD

**Issue by mrneo240** [sonik-br/GDMENUCardManager#10]
Hello,

How can I compile each flavor of build for my fork?

**Comment by sonik-br** [comment]
Hi,
I only build from inside VS (2019).

The project "GDMENUCardManager" is for windows only.
"GDMENUCardManager.AvaloniaUI" is multi platform UI.

Here's my settings for publishing each one:

Windows
![image](https://user-images.githubusercontent.com/16923826/121519750-78aa4900-c9c8-11eb-83b6-799e4caa2022.png)

Linux (can change the target runtime to mac/win if desired)
![image](https://user-images.githubusercontent.com/16923826/121519778-7fd15700-c9c8-11eb-918f-cfaba8c77752.png)

It's possible to build on [command line](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) too.

If you find any bug or add new feature please share it here too :)

**Comment by mrneo240** [comment]
Thank you!
I settled on using these for now for my releases:
```
dotnet publish -c Release -r linux-x64 --self-contained false  -o ./publish/linux-x64 .\GDMENUCardManager.AvaloniaUI\GDMENUCardManager.AvaloniaUI.csproj

dotnet publish -c Release -r osx-x64 --self-contained false -o ./publish/osx-x64 .\GDMENUCardManager.AvaloniaUI\GDMENUCardManager.AvaloniaUI.csproj

dotnet publish -c release -r win-x64 --self-contained false -o ./publish/win-x64 .\GDMENUCardManager\GDMENUCardManager.csproj
```
