### ISSUE TITLE
GDI Shrink - Lista de Jogos Compatíveis e porque não está bloqueando quando selecionado blacklist

### ISSUE THREAD

**Issue by tsuihak** [sonik-br/GDMENUCardManager#15]
Primeiramente, parabéns pelo excelente trabalho. Estou utilizando a última versão no Windows 10. Quero relatar alguma coisa e não tenho certeza se estou fazendo certo. Quando escolho a opção GDI Shrink seleciono todas as opções, inclusive a blacklist. Pelo que entendi os jogos da blacklist deveriam ser reconhecidos e não deveriam ser shinkados se podemos dizer assim. Vi alguma lista que o Resident Evil 2 não funciona quando selecionado shrink mas mesmo assim o programa faz o shrink mesmo assim. Gostaria de saber onde vejo essa lista oficial que o programa reconheça os jogos como blacklist.
Outros problemas ou melhoria:
1 - Não vi a opção se SHRINK na versão do MacOS.
2 - Poderia ter um aviso que estamos colocando jogos repetidos com o mesmo ID antes de passarmos para o cartão. Só não peço para bloquear jogos repetidos porque as vezes o pessoal faz modificações nos jogos e eles continuam com o mesmo ID.

**Comment by sonik-br** [comment]
Oi,
Confira por favor se o id do seu jogo está na blacklist. É so segundo campo no arquivo gdishrink_blacklist.txt.
Por exemplo no resident evil 2 versão americana é T1205N.
O aplicativo deveria funcionar exatamente como você descreveu. Se ativar a blacklist, ele não deveria aplicar shrink nesses jogos.
Se o id estiver correto e mesmo assim não funcionar, me avise.
Ah, o shrink só é aplicado no momento de copiar o jogo para o cartao. Se o jogo ja estiver no cartao, ele nao faz diferença alguma.

A versão de windows possui mais recursos mesmo, devido principalmente a alguns detalhes tecnicos. Ela é a unica versão que executa programas externos (por exemplo o shrink).
Se a versão de windows for uma opção para voce, recomendo que utilize ela. Uma grande vantagem é poder arrastar e soltar os jogos do explorer para dentro do app, e tambem poder arrastar e reordenar os jogos que estão na lista.

O ID é problematico pois varios _homebrews_ usam o mesmo id. Algums jogos de atomiswave usam tambem.
Tenho alguns recursos para adicionar ainda mas me falta tempo. Queria fazer uma tela de relatorio com alguas informacoes, inclusive de jogos repetidos. Por enquanto estou aguardando o [OpenMenu](/mrneo240/openmenu) ficar pronto, para então tentar adicionar mais recursos no meu app.

**Comment by tsuihak** [comment]
Obrigado pela ajuda. Deu certo aqui e resumindo o release que tinha do Resident Evil não funcionava. Se não quiser ouvir a explicação já pode parar por aqui. Tenho releases do tipo .bin e .cue da redump. Usava o programa gdidrop para converter os arquivos e estava dando certo até esse jogo. Baixei outra versão americana já como GDI e o programa funcionou como deveria, ou seja, não fazer shrink para jogos blacklist. Me desculpe pelo inconveniente e parabéns pelo programa. Funcionar perfeito quando não há erro pelo usuário. kkkkkk.

Com relação aos feedback do descrito acima, estou dando preferência ao Windows mesmo. Não dá para ficar sem a função shrink.

**Comment by sonik-br** [comment]
Que bom que funcionou :)
Sobre os releases, a cena de dreamcast recomenda utilizar os TOSEC, pois já estão no formato correto e são compatíveis.
