### ISSUE TITLE
Feature request: Native support for game covers

### ISSUE THREAD

**Issue by thamulot** [sonik-br/GDMENUCardManager#16]
Hi,
I'm new to modding a Dreamcast. I modded so many different consoles, from the Nintendo Minis (Hakchi2) to the PS2 (OPL Manager) and up to the Dreamcast, it was super easy to download and "apply" game covers.

I think it would be really neat if GMENUCardManager could leverage a database of covers - for example https://archive.org/download/670dreamcastgamesjewelcoverpicturesconvertedto256x256.pvrfilesforgdemu.7z - and automatically modify / patch GDI files on the fly when saving changes to the SD card.

Right now, the best way the community has come with is to use https://segaxtreme.net/threads/release-easy-0gdtex-pvr-tools.24651/ and play with decompressing and rebuilding tosec GDI images with drag and dropping folders on Windows batch scripts. Maybe GMENUCardManager could leverage this mechanism behind the scene to streamline the whole process combined with the covers database.

Anyway. I open this issue so we can kick-start a discussion / analyzing on the requirements and feasibility of such a thing in GMENUCardManager.

Regards,

**Comment by sonik-br** [comment]
Hi,
Please wait for [OpenMenu](/mrneo240/openmenu). I think it will be easier to change the cover images.
No need to inject/recreate the GDI file as it will load from an external file.
