### ISSUE TITLE
OSX version not working with OpenMenu

### ISSUE THREAD

**Issue by billdisney** [sonik-br/GDMENUCardManager#18]
I am able to get OpenMenu to work using the Win-X64 version of GDMENUCardManager.  I can build an SD Card of games and it will boot properly on the Dreamcast and the UI of OpenMenu seems to work perfectly for navigating and launching games.;

However, when I do scratch build of my SD card using the OSX version of GDMENUCardManager, I put it in my Dreamcast and after going through the initial Dreamcast and Sega screens, I just get a black screen.

Also tried taking an SD Card built initially under Win-X64 version of GDMENUCardManager for use with OpenMenu, tested it in the Dreamcast and was working fine with OpenMenu, then took the same SD card and tried to update it using the OSX version of GDMENUCardManager.  It boots into a black screen after the initial Dreamcast and Sega screens just like the scratch built card.

**Comment by sonik-br** [comment]
Hi.
It's not supposed to work with OpenMenu (yet). You have to use mrneo240's [fork](https://github.com/mrneo240/GDMENUCardManager) for now.
