### ISSUE TITLE
error: cannot create a file that its already exist?

### ISSUE THREAD

**Issue by rooster87** [sonik-br/GDMENUCardManager#20]
Been having issues giving a error : cannot create a file that its already exist. How can i fix this isuue>?

**Comment by sonik-br** [comment]
Need more details.
Like version of app. If it worked previously. When the error occurs.

**Comment by rooster87** [comment]
Even previous version.

**Comment by rooster87** [comment]
![image](https://user-images.githubusercontent.com/47829443/145735094-14c96ec8-cb33-48b7-8b41-d43790ea9b6b.png)

**Comment by rooster87** [comment]
@sonik-br 
![image](https://user-images.githubusercontent.com/47829443/145735131-9de2fce2-a140-48aa-bd55-2e34a3b5d2b7.png)

**Comment by rooster87** [comment]
> Need more details. Like version of app. If it worked previously. When the error occurs.

**Comment by sonik-br** [comment]
Please just open the app and click on "Preload" before save. Let's see what's happen.

**Comment by rooster87** [comment]
> Please just open the app and click on "Preload" before save. Let's see what's happen.

It did the same thing :(

**Comment by sonik-br** [comment]
What steps are you doing inside the app?
Adding a game?
Removing? Renaming?
Changing order...

**Comment by rooster87** [comment]
> What steps are you doing inside the app? Adding a game? Removing? Renaming? Changing order...

ok first time it asked me to NET 5.0 on my windows 10 i used your latest version i already used the same card in a different gdmenu so i installed your dgmenu everything ran good i followed a youtuber to change the menu i use it on my japanese dremcast it worked but when i added  more games on the gdemu it started to pop up that error message.

**Comment by sonik-br** [comment]
Try loading the app then click on save. Don't add/remove/rename any game.
Let's see if this works.

**Comment by rooster87** [comment]
Thats what i been trying to do still that message pops up.

**Comment by sonik-br** [comment]
Can you try with another empty card?

**Comment by sonik-br** [comment]
Closing as I did not get any response for a long time. Feel free to reopen if needed.
