### ISSUE TITLE
Linux SD Directory nof found

### ISSUE THREAD

**Issue by pseiler** [sonik-br/GDMENUCardManager#27]
I have the issue with linux that my sd card isn't found. Could you add an option to simply choose from a directory for linux systems. This would simplify the process and should work for all desktop environments.

Otherwise the application looks like it's working fine.

OS: openSUSE 15.3
Windowmanager: i3

**Comment by sonik-br** [comment]
I've added an debug feature that does this. You can try to see if it works on your OS.
Edit the `.conf` file and set `ShowAllDrives` to `True`

**Comment by pseiler** [comment]
This works like a charme. @sonik-br could you add this to the README.md?

**Comment by sonik-br** [comment]
This is dangerous and if not correctly used can wipe the data of the selected drive/mount. The "feature" is there only for debug.

The correct way would be to debug why it does not work with this specific distro.
I can install it on a VM but it will take time. Too many projects right now.

**Comment by pseiler** [comment]
Is there a way to help you debug this?

**Comment by sonik-br** [comment]
Any experience in building dot net app on linux?

**Comment by pseiler** [comment]
Unfortuantely not. I have experience with Makefiles and using gcc and stuff. But I haven't done anything with dotnet related yet.
Only compiled a new version of Mono for my distribution somewhen.

**Comment by sonik-br** [comment]
I will try to to an debug build for you but this will take time.
Leave this issue open and I will reply here later.

**Comment by sonik-br** [comment]
@pseiler did you get the change to test the linked version?

**Comment by pseiler** [comment]
Not yet. I'll try it next week. Unfortunately I'm on vacation til then.
