### ISSUE TITLE
Error during GDIShrink

### ISSUE THREAD

**Issue by elijah0067** [sonik-br/GDMENUCardManager#28]
I'm trying to use the GDI shrink functionality on the GDMENU Card Manager. Upon trying, I'm getting this error:
![image](https://user-images.githubusercontent.com/24557536/175335973-68699e65-6144-40e0-be15-aaf0b295982a.png)

I did a little bit of troubleshooting trying to make things work:
1. My game is compressed (7zip). I tried extracting the GDI files then clicking the 'Add game(s)' on the manager still error.
2. I tried to search a little bit and found out that GDIshrink is based on [gditools](https://sourceforge.net/projects/dcisotools/), so I downgraded my Python 3 to Python 2.7. Still did not work.
3. I also tried running the app with administrative privilage.

Am I doing something wrong?

**Comment by sonik-br** [comment]
GDIshrink is compiled as an exe and does not require installing the stand alone Python.
Compressing any other game works?
No need to run as admin as long as the current user can write to the card and can read the game files from your local disc.

**Comment by elijah0067** [comment]
So I tried using a different PC and a different game. Still no luck.

![image](https://user-images.githubusercontent.com/24557536/175440474-2b4ba96d-e0ef-4e19-9267-13a8127e0af8.png)

**Comment by sonik-br** [comment]
Adding games with gdishrink disabled works?

**Comment by elijah0067** [comment]
Yes. Also works fine on dreamcast but takes approximately 1.1GB in space.

**Comment by sonik-br** [comment]
Sorry but I don't know why it's not working.
You can download ready to use, gdishrinked games. There's a site with **dreamcast talk** with links to download those games. I can't share it here but pretty easy to find ;-)
You can also run the python version of gdishrink before adding the games and not use the internal version.

**Comment by elijah0067** [comment]
Hi! Upon further testing the issue was my dump files were bad. 

Currently, what i've been doing was getting my games from a Redump set, then converting the games using 'Redump CUE to GDI'. Now it works fine.

This is the file structure of the games not converted from Redump looks like:
![No Raw](https://user-images.githubusercontent.com/24557536/175782638-917817ae-6c38-4482-ae2f-e7a276c9897c.PNG)

This is the file structure of the games converted from Redump looks like:
![Convert from Redump](https://user-images.githubusercontent.com/24557536/175782649-b6e2352b-c603-4b9e-83d1-c76404076287.PNG)

GDI compression work fine now. 

A side question, will you add region free patches and VGA patches in the future?

**Comment by sonik-br** [comment]
The community recommends to use Tosec rips and not Redump.
I have not looked into Redump files to see why they are not compatible.

No plans to patch game files.
Region free and VGA enable should be implemented on the loader. GDMenu does this and I think openMenu also does.
