### ISSUE TITLE
Issue with TOSEC releases and shrinking

### ISSUE THREAD

**Issue by ChronoStriker1** [sonik-br/GDMENUCardManager#3]
TOSEC has files named .raw where the shrink expects a .bin

**Comment by sonik-br** [comment]
Hi. Can you provide more details? What's not working?

**Comment by ChronoStriker1** [comment]
![image](https://user-images.githubusercontent.com/2432904/108442894-d6eaca80-7225-11eb-9143-a93466ccc9ea.png)
Looking at the files that were extracted to that location:
PS H:\07> dir


    Directory: H:\07


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        2/18/2021   8:11 PM          98304 track03.iso
-a----        2/18/2021   8:12 PM      699158528 track04.iso
-a----        2/18/2021   8:12 PM         356352 track01.iso
-a----        2/18/2021   8:12 PM         705600 track02.raw
-a----        2/18/2021   8:12 PM            113 AeroWings 2 - Airstrike v1.001 (2000)(Crave)(US)[!].gdi

**Comment by ChronoStriker1** [comment]
Also it looks like the crash handler locks the folder so you cant delete it or remove the game and save changes until the program is closed

**Comment by sonik-br** [comment]
Ok I will look into it.
Which operating system? 32 or 64 bits?
Also, you are shrinking from another device to the sd card right? Shrinking files that are already on the card will not work.

**Comment by ChronoStriker1** [comment]
Windows 10 Pro 1909 - x64
And yes I'm shrinking files that are stored on my nas, that is mapped to a drive letter, in this case z:\

**Comment by sonik-br** [comment]
Just tested with the same game and it worked.
How are you adding the game to the list? By clicking on + or by drag-and-drop?

**Comment by ChronoStriker1** [comment]
I am hitting the +

**Comment by sonik-br** [comment]
Ok found it.
Your file is compressed right? There is a problem with shrinking compressed files.
I will fix it today or tomorrow.
For now you can just decompress the file to a folder on your pc, then add it to the manager.

**Comment by ChronoStriker1** [comment]
That does seem to work, it will take a while for me to unzip the entire tosec library so Ill just start with USA tonight until you get a chance to work on it :D

**Comment by sonik-br** [comment]
Fixed :)
Thanks for reporting it.

**Comment by Techsteps** [comment]
Does this mean I can leave my DC games zipped now? Just checking before I spend time unzipping all of them. :)

**Comment by sonik-br** [comment]
The app will unzip them when transferring from pc to the sd card.
Please note that compression format support varies from windows to linux/mac version.
Also note that some info about the game can only be read after extraction. Like IP.BIN info and 0GDTEX image. Those are extra features and will not impact the usage. Info will show on app after the files are transferred to the card.
