### ISSUE TITLE
Unlicensed GDI

### ISSUE THREAD

**Issue by L10N37** [sonik-br/GDMENUCardManager#31]
Won't allow unlicensed GDI , no big deal, but list was cut short of 13 unlicensed games.

**Comment by sonik-br** [comment]
Hi.
What happens? I have no idea about those "13 unlicensed games".

**Comment by L10N37** [comment]
On the old version the games just have no name. On this one, it simply compiles a list and tells you it's ignored those files.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sonik-br** [comment]
Which old version? What games?
Without more details, it's impossible to help.

**Comment by L10N37** [comment]
The madsheep version/s.

All unlicensed games, pier solar as 1 example.
Another is an unlicensed port from some other obscure JP console.
There were 13 in total.

TBH the library was a full verified set, but in BIN/CUE. I had to convert the entire set to GDI after removing the fat.

Unfortunately, 1 in 5 games wont work and aren't recognised as game discs.

Because some of the games definitely worked when found elsewhere, and already in a suitable format, I know it's not incompatibilities so I've moved on to the TOSEC dump.




Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by L10N37** [comment]
I think i found the cause of some games not working, I think it's any game with more than 3 bin files. I guess you'd have to convert them to single bin, then to GDI.. not that helps with the (UNL) images, but good to note.

**Comment by sonik-br** [comment]
Good to know. My app uses an library to read GDI files.
I can debug to see if the lib supports those games or if it's a faulty on my side.

Anyway, homebrews are generally in CDI/MDS/CCD format and not on GDI format.

I won't have time to debug this in the near future. Closing this now but I will update here if/when I found out more about this problem. Thanks for reporting.

**Comment by L10N37** [comment]
As mentioned the entire set was in BIN/CUE. I tried GDI drop and it worked, so I found awfulbears update that allowed automated batch for the entire library.  This is how I have them all as GDI

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sonik-br** [comment]
I tested with piersolar converted to GDI.
The conversion tool generated a GDI file, plus track1.raw (audio) and track2.bin (data).
Even the `GDRom Explorer` tool can't open this image.
This converted game works on the dreamcast?

**Comment by L10N37** [comment]
Yes, that's normal. GDI is similar to Cue as it's also a descriptive text format.

as mentioned, the unlicensed games are a no no in this version of GDmenu card manager. It won't allow me to add them at all, so I wouldn't know if they work.

here's an example of a worker/s and a non-worker from the Redump library.

Resident Evil 3 (USA) converted from BIN/CUE to GDI. Working.

Dino Crisis (USA), converted as above from the same redump library,  working.

Resident Evil: Code Veronica (USA) , converted as above from the same redump library.

There are many more that worked, but I obviously didn't go through over 300 games and try them all.

now a broken image that isn't recognised.

Resident Evil 2 (Tried both EURO PAL/ NTSC US)
Disc 1 and Disc 2, both broken.

Again, off memory...  There are many more broken.
Add Pier Solar to that list.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sonik-br** [comment]
Well you can put the game as a folder directly on the card and not use any manager.
And try if it load using gdemu. I think it will not work. But please test it.

**Comment by L10N37** [comment]
OK I will test that within the next few days 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
