### ISSUE TITLE
Won't See SD Card

### ISSUE THREAD

**Issue by InaliRahl** [sonik-br/GDMENUCardManager#34]
I am using version 1.3.5 on macOS 13, and the program won't see my SD card. Works fine in Windows 11 with the same machine and program.

I have given it full disk permissions just in case and that did not help.
![Screenshot 2022-10-28 at 2 26 38 PM](https://user-images.githubusercontent.com/69852220/198706914-51ff7820-f936-4114-ada0-2da006d414bd.png)

**Comment by sonik-br** [comment]
Hi,

Please take a look at: https://github.com/sonik-br/GDMENUCardManager/issues/32#issuecomment-1220194873

And paste the contents here. I need this info to see why it won't show the card.

**Comment by sonik-br** [comment]
Closing as I've not received any feedback.
