### ISSUE TITLE
macOS: GDI Shrink?

### ISSUE THREAD

**Issue by davidnewhall** [sonik-br/GDMENUCardManager#35]
Is this checkbox supposed to be on macOS? Is there another way to enable this?

![Screen Shot 2022-11-21 at 8 01 00 PM](https://user-images.githubusercontent.com/2402929/203218190-d87c5dfa-daf3-4485-8789-60aca1c4fe93.png)

**Comment by sonik-br** [comment]
Windows only.
Not planned on other platforms as it requires external tool.

**Comment by davidnewhall** [comment]
Thanks for the reply. What tool? Is it open source?
