### ISSUE TITLE
Games don't boot after shrink

### ISSUE THREAD

**Issue by jrfbal** [sonik-br/GDMENUCardManager#37]
Hello,

I'm using a gdemu 5.20.3 and the games work fine when using complete gdi images, however when I try to shrink and run them it boots directly to the Dreamcast menu.

These games are not blacklisted.

Thank you

**Comment by sonik-br** [comment]
Hi,

This happens with all tested games or only with some?
Using TOSEC releases? Redump releases are know to cause problems...

**Comment by jrfbal** [comment]
Hello,
I made some further testing and seems that is only with some.
I've tried with Crazy Taxi, Crazy Taxi 2, SEGA SMASHPACK VOLUME 1, Soul Calibur and Shadow Man. From these both Crazy Taxi and Soul Calibur don't work.
For these titles, the cd art is no longer displayed in both GD Menu and GDMENUCardManager, so seems to me that something in the shrink is not working correctly.
I'm using TOSEC.

**Comment by sonik-br** [comment]
My app uses a 3rd party too to appy gdi shrinking.
Please test with it
https://sourceforge.net/projects/dcisotools/
Let's identify what's causing the problem.
BTW there's one site with Talk about Dreamcast that have most of the games already shrinked and ready to use... Easy to find.
