### ISSUE TITLE
macOS Support Testing

### ISSUE THREAD

**Issue by marcomorain** [sonik-br/GDMENUCardManager#4]
Hi @sonik-br - thank you so much for making this tool.

I'm testing the macOS support right now.

The first issue that I hit was this:

```
$ ./GDMENUCardManager
Failed to load Q, error: dlopen(/Users/marc/Downloads/GDMENUCardManager.v1.3.0-osx-x64/libhostfxr.dylib, 1): no suitable image found.  Did find:
	/Users/marc/Downloads/GDMENUCardManager.v1.3.0-osx-x64/libhostfxr.dylib: code signature in (/Users/marc/Downloads/GDMENUCardManager.v1.3.0-osx-x64/libhostfxr.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
The library libhostfxr.dylib was found, but loading it from /Users/marc/Downloads/GDMENUCardManager.v1.3.0-osx-x64/libhostfxr.dylib failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366
```

I worked around this [using these steps](https://github.com/Jackett/Jackett/issues/5589):

```
$ xattr -p com.apple.quarantine libhostfxr.dylib
0081;602eb0c6;Firefox;81D3CB12-3C53-4EE2-81B3-FB10DD979D0B
$ xattr -w com.apple.quarantine "00c1;0081;602eb0c6;Firefox;81D3CB12-3C53-4EE2-81B3-FB10DD979D0B"  *.{dylib,dll}
$ ./GDMENUCardManager
```

And it launched fine.

**Comment by marcomorain** [comment]
![image](https://user-images.githubusercontent.com/448001/108497628-a6e20c80-72a3-11eb-8faf-1e4641436900.png)

It's looking good so far, going to test some writes now.

**Comment by marcomorain** [comment]
@sonik-br it's working great. I've added games to my card and they are booting on the Dreamcast.

**Comment by Pistacchione** [comment]
Hi,

I tried to open but I always received permission denied. I'm on MacOS 11.3

```
 ./GDMENUCardManager
 permission denied: ./GDMENUCardManager
```

I also tried with `sudo   ./GDMENUCardManager` with no luck.

Maybe I need to install some .NET packages?

Thanks

**Comment by sonik-br** [comment]
Glad you got it working.

**Comment by Born2beSlicker** [comment]
Hi, I joined here specifically for this tool. I’m not educated in coding or anything, so I’m sorry for being a bother.

Could it be possible to make a guide for how to get this working on MacOS? I can’t get it to work but have no experience in editing files to fix it like it’s suggested above.

I’m just too used to download, install, double click and it runs.

**Comment by sonik-br** [comment]
Hi @Born2beSlicker.
Sorry but I don't even have a mac to test it.
You will have to run some commands on the terminal.

**Comment by Pistacchione** [comment]
@Born2beSlicker if you want you can download the latest version of GDMENUCardManager ready for MacOS here

[https://mega.nz/file/l7oAwA7L#kPHH10qgbESv69_ib7ETmw82f5JiiY5Xdy1424K4VMk](url)

This is an app bundle made by me. Simply unzip in any folder al launch it like any other mac application.

**Comment by Born2beSlicker** [comment]
> @Born2beSlicker if you want you can download the latest (1.3.2) version of GDMENUCardManager ready for MacOS here
> 
> [https://mega.nz/file/l7oAwA7L#kPHH10qgbESv69_ib7ETmw82f5JiiY5Xdy1424K4VMk](url)
> 
> This is an app bundle made by me. Simply unzip and launch it like any other mac application.

Oh, wow, that worked right away. Thank you so much for doing this. I truly appreciate you helping me (and anybody in future who finds this) out.

**Comment by sonik-br** [comment]
Nice!
This is something I can do on windows? It requires signing the app with a dev id?

**Comment by Pistacchione** [comment]
> Nice!
> This is something I can do on windows? It requires signing the app with a dev id?

No, dev id is not needed. 

If you want to use it for mac os release simply download the zip file, unzip it and you will find a folder call `GDMENUCardManager.app` (mac os application bundle are folders).

Update the `GDMENUCardManager` folder inside `Contents/MacOS` with the new version and update the `Info.plist` file version number. `Info.plist` file is an xml file.

The keys to update are `CFBundleShortVersionString` and `CFBundleVersion`

If you need help feel free to ask

**Comment by sonik-br** [comment]
No need to chmod and xattr the files inside the bundle?

**Comment by Pistacchione** [comment]
> No need to chmod and xattr the files inside the bundle?

No is not needed, mac os should present a window like this

![immagine](https://user-images.githubusercontent.com/11761177/122951947-f5043b00-d37d-11eb-993f-82cac517a38b.png)

And user should go to Security & Privacy and click the Open Anyway button in the General pane

![immagine](https://user-images.githubusercontent.com/11761177/122952208-2aa92400-d37e-11eb-8a11-08593a941714.png)

Here a link to apple documentation regarding Safely open apps on your Mac
[https://support.apple.com/en-us/HT202491](url)

**Comment by sonik-br** [comment]
Thank you!
I will offer this appimage too on the download page.

**Comment by adamfratino** [comment]
> @Born2beSlicker if you want you can download the latest (1.3.2) version of GDMENUCardManager ready for MacOS here
> 
> [https://mega.nz/file/l7oAwA7L#kPHH10qgbESv69_ib7ETmw82f5JiiY5Xdy1424K4VMk](url)
> 
> This is an app bundle made by me. Simply unzip and launch it like any other mac application.

@Pistacchione seems the mega link is down. do you still maintain this?

**Comment by Pistacchione** [comment]
Hi @adamfratino ,

I remove the link because is not needed anymore, now all the versions works on macOS, just download it fron Github release page

**Comment by adamfratino** [comment]
I noticed after I posted but I didn't want to delete my question in case other people see it, thanks for the reply!

**Comment by AnimeFunTV** [comment]
Any word on whether an Apple Silicon/ARM port will be made? macOS 27 will be the last version that will allow x86/Rosetta apps.

**Comment by sonik-br** [comment]
I don't use a mac... So x86 won't be supported anymore? This is news to me.
I can try to build it for ARM but I have no way of testing.

**Comment by AnimeFunTV** [comment]
Correct, the new release of macOS 27 (which was just released this month) dropped all support for Intel-based Macs (ie., it's Apple Silicon/ARM Mac's from here on out). 

[Mac Rumors: macOS 27 Golden Gate Is the Last to Support Intel Apps via Rosetta 2](https://www.macrumors.com/2026/06/10/macos-golden-gate-last-to-support-intel-apps/)

You would still able to run intel/x86 apps on macOS 27 via rosetta translation on Apple Silicon/ARM Mac's but come next OS, macOS 28 (planned to release fall of 2027) will no longer be able to run intel/x86 apps as it will no longer contain the rosetta translation layer that allowed those apps to run on Apple Silicon/ARM Mac's

I have a M4 MacMini, I could offer my assistance to test the app function, although I never done something like that so I hope my results are useful.

Or you could look for a M1 Mac Mini or M1 MacBook Air, those are the cheapest used Apple Silicon out there.

**Comment by sonik-br** [comment]
I can't afford to get a mac. It's like the price of two dreamcasts where I live. And getting a working dreamcast is more important since I have none.

Please try the arm build from [here](https://github.com/sonik-br/GDMENUCardManager/releases/tag/v2.1.0-pre).
