### ISSUE TITLE
feature request - Officially support Rhea and Phoebe

### ISSUE THREAD

**Issue by filipe-maia** [sonik-br/GDMENUCardManager#40]
Hi.
Almost every tutorial on the web uses SDCardMakerForGDEMU by MadSheep to easily setup the SD Card for the Rhea and Phoebe (with VGA, Region and Menu off).
I've tried to do the same with  GDMENUCardManager unsuccessfully.
Seems to be easy (but I might be mistaken) to officially support the Phoebe and Rhea on GDMENUCardManager.
If the creator of RMenu for Phoebe/Rhea doesn't give permission to use his application on yours, just leave the 01 folder empty.
Thanks.

**Comment by filipe-maia** [comment]
I have a GDEMU, a Phoebe and a Rhea. The folders naming is the same for GDEMU, Phoebe and Rhea.
I'm currently trying to write a script in Java to manage my SD Card for Rhea/Phoebe. Maybe I'll have it ready next week. After that, if you have time, maybe you could check it out and see if it would be easy for you to port it to GDMENUCardManager or to a new app based on GDMENUCardManager.

**Comment by sonik-br** [comment]
Ok. I can take a look but can't promise to make a app/feature for it.
