### ISSUE TITLE
feature request - Format SD Card

### ISSUE THREAD

**Issue by filipe-maia** [sonik-br/GDMENUCardManager#41]
Give the option to format the SD Card in FAT32 32kb/64kb clusters.
This way the user won't need to use another tool.

**Comment by filipe-maia** [comment]
This feature request might be time consuming to be developed.

**Comment by sonik-br** [comment]
I don't know of any reliable way to do this from inside the app.
Card formatting is a one time process and I think it's fine to let the user handle this job

**Comment by filipe-maia** [comment]
I think that you are correct. Maybe in the future if you want and if you gain knowledge on how to do it, you can implement. But if you don't implement, it's not a big deal.
