### ISSUE TITLE
feature request - Convert from BIN/CUE to Another Image Type

### ISSUE THREAD

**Issue by filipe-maia** [sonik-br/GDMENUCardManager#42]
Just like the title says.
This might be difficult to implement.

**Comment by filipe-maia** [comment]
If you are afraid that the new image type might contain a bug, you can just give a warning like "The converted image might not work, do not report it as a bug".

**Comment by sonik-br** [comment]
This is for Redump releases?
Every Redump title I've tried to convert gave me an invalid gdi file.

**Comment by filipe-maia** [comment]
Hi. Yes, for redump releases. I must admit, I've never tried to convert Dreamcast games from redump to gdi format. I just know that for Sega Saturn there are the following scripts, so I thought thought that for the Dreamcast it would be simple:
https://notabug.org/mai/ssrptc

**Comment by sonik-br** [comment]
Please try the tools and let me know if you can load the resulting gdi files.
What I've seen all over the internet is: "use tosec releases. don't use redump releases."
