### ISSUE TITLE
MacOS version does not list a sd card in a card reader

### ISSUE THREAD

**Issue by endiny** [sonik-br/GDMENUCardManager#43]
SD card is mounted to `/Volumes/<SD card label>`, but the app lists only `/System/Volumes` mount points.
<img width="284" alt="image" src="https://github.com/sonik-br/GDMENUCardManager/assets/3712944/4c0e7bdd-acb1-4005-a139-e7d41a4a66ac">

As a workaround I would appreciate an ability to enter a custom path (at my own risk)

**Comment by savaughn** [comment]
I'm on macOS 13.x M1. The latest v2.0.0 and v2.0.0-TESTING both auto-detect the SD card.

Tested: 
- Sd card already inserted before application startup
- Sd card inserted after application startup with refresh button

**Comment by sonik-br** [comment]
Thanks for confirming it.
Closing as the issue was fixed.
