### ISSUE TITLE
No usable version of libssl was found issue.

### ISSUE THREAD

**Issue by arroyjose** [sonik-br/GDMENUCardManager#45]
I tried running your program on Ubuntu 22.04 and I'm getting this error:

No usable version of libssl was found

Did a quick search online and it seems like it's an issue with the library being older than the one in Ubuntu.  Is GDEMUCardManager supported on Ubuntu 22.04?  If yes, can you please add some notes to your README about how to get it to work?

**Comment by sonik-br** [comment]
Hi.
I don't have access to a linux machine to test the app.

There's an updated version "Test version (Pre-release)" on the releases page.
Please try with this version and let me know if it fix the problem.

**Comment by arroyjose** [comment]
Awesome.  Yes, your test version opens up on Ubuntu without issue.  Thanks!

**Comment by sonik-br** [comment]
Thanks for reporting it!
