### ISSUE TITLE
[Feature request] MAME CHD support

### ISSUE THREAD

**Issue by JuanVCS** [sonik-br/GDMENUCardManager#5]
Would be cool even if it was invoking chdman.

**Comment by sonik-br** [comment]
Afaik gdemu does not support CHD format.

**Comment by JuanVCS** [comment]
Maybe I phrased it wrong, I converted a bunch of games to CHD format with MAME'S chdman utility.
So it'd be nice if GDMENU Card Manager supported converting them back to GDI, even if it's just calling `chdman extractcd -i game.chd -o game.gdi`

**Comment by sonik-br** [comment]
Got it. But I still don't understand how this would be useful. CHD is not a file format used for dreamcast.

**Comment by JuanVCS** [comment]
It's as useful as 7z or rar support. A compression format that people use to store their collections.

**Comment by sonik-br** [comment]
Understood. Might be handy for people storing the games using this format.
But I currently have no plans for adding new features. A lot of ideas but no time to do it.
I started worked on a disc image browser/extractor and a gdmenu theme manager but had to drop it.

**Comment by sonik-br** [comment]
Closing this for now.
I might look into this feature again in the future.
