### ISSUE TITLE
Link to github closes the app

### ISSUE THREAD

**Issue by pipechaves** [sonik-br/GDMENUCardManager#55]
**Describe the bug**
When going to the about section and clicking the link, the app closes

**To Reproduce**
1. Go to 'the about section.'
2. Click on 'the link'
3. See error - > App closes

**Expected behavior**
Open default browser on the github link

**Screenshots**
![image](https://github.com/sonik-br/GDMENUCardManager/assets/22892247/eb72b73b-f7df-4bb7-b348-90646fc7b9ab)

**Desktop (please complete the following information):**
 - OS: windows 10 
 - 
![image](https://github.com/sonik-br/GDMENUCardManager/assets/22892247/65c8cbbe-313d-4288-85fd-5ba551bc36e8)

 - Browser [Brave]
 - Version [Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by sonik-br** [comment]
Thank you.
Going to fix it for the next release.

**Comment by savaughn** [comment]
Not reproducible on MacOS with v2.0.0
