### ISSUE TITLE
GDI SHRINK doesn't show on Linux

### ISSUE THREAD

**Issue by filipe-maia** [sonik-br/GDMENUCardManager#57]
Hi.
Just as the title says.
I'm on Linux Mint 21 and I'm using version 2.0.0.
See screenshot.
Thanks.
![screenshot](https://github.com/sonik-br/GDMENUCardManager/assets/9107130/bb62af8f-2718-408d-bea9-f9179da2e426)

**Comment by sonik-br** [comment]
The GDI Shrink feature is indeed only available on the Windows build.
