### ISSUE TITLE
deleting my gdmenu from 01 folder

### ISSUE THREAD

**Issue by aihooo444** [sonik-br/GDMENUCardManager#6]
every time i make any change it completes but then deletes the disc.cdi in my 01 folder it does leave a 1kb disc.gdi file in its place but that does not work

**Comment by aihooo444** [comment]
Ok i figured it out you have to have the gdi version of gdmenu you cant have the cdi version now all works

**Comment by sonik-br** [comment]
Yes. Current version uses gdi for the menu. It's more compatible with dreamcast.
