### ISSUE TITLE
Please add also the automount path '/run/media/username/'

### ISSUE THREAD

**Issue by cinnamonmatexfce** [sonik-br/GDMENUCardManager#7]
The linux (and mac) version is almost ready. I just need to do some tests.
What distro do you use?
I'm testing on Ubuntu on a VM. It mounts my card reader on /media/.... It''s the common way to handle removeable storage devices?

_Originally posted by @sonik-br in https://github.com/sonik-br/GDMENUCardManager/issues/2#issuecomment-775885550_

**Comment by cinnamonmatexfce** [comment]
In ArchLinux (KDE) the default automount path is `/run/media/username`, where `username` is the username of the currently logged-in user.


... I wish distros have a unique common standardized _FileSystem Hierarchy_ across all of them... Meh...

**Comment by sonik-br** [comment]
Hi. I tested it on Ubuntu running on a VM.
The path appears on the mount list for you?
From what I remember it will only list devices mounted on "/media/"...

**Comment by cinnamonmatexfce** [comment]
> Hi. I tested it on Ubuntu running on a VM.
> The path appears on the mount list for you?
> From what I remember it will only list devices mounted on "/media/"...

Yup, was made an upstream decision by `udisks` devs back in 2012. See here more infos: https://cgit.freedesktop.org/udisks/commit/?id=aa02e5fc53efdeaf66047d2ad437ed543178965b

Don't ask me why some distro use `/media` or some others use `/run/media`

**Comment by sonik-br** [comment]
When you run GDMENUCardManager it shows the card on the "SD Card" list?

**Comment by cinnamonmatexfce** [comment]
> When you run GDMENUCardManager it shows the card on the "SD Card" list?


Nope: the dropdown menu appears but it's empty 'cause it's expeting to find `something` under `/media` which is not.

**Comment by sonik-br** [comment]
Please override your executable with this one and test.
You will need to add execute permission to the file.

[GDMENUCardManagerKDE.zip](https://github.com/sonik-br/GDMENUCardManager/files/6497019/GDMENUCardManagerKDE.zip)

**Comment by cinnamonmatexfce** [comment]
> Please override your executable with this one and test.
> You will need to add execute permission to the file.
> 
> [GDMENUCardManagerKDE.zip](https://github.com/sonik-br/GDMENUCardManager/files/6497019/GDMENUCardManagerKDE.zip)
> 

I'll try as soon as I'll be in front of my PC. Really fast btw. Thanks

**Comment by cinnamonmatexfce** [comment]
> [GDMENUCardManagerKDE.zip](https://github.com/sonik-br/GDMENUCardManager/files/6497019/GDMENUCardManagerKDE.zip)

Does NOT work unfortunately... Still no devices in the dropdown menu.

```
$ lsblk -f

sdi                                                                                                  
└─sdi1      vfat              FAT32 GDMENU       DE86-1138                               7,4G    50% /run/media/$USERNAME/GDMENU
```

**Comment by cinnamonmatexfce** [comment]
As a workaround one can `--bind` mount the `/run/media/$USERNAME/something` into (create the directories first!) `/media/something`

```
$ mount

/dev/sdi1 on /run/media/$USERNAME/GDMENU type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)
/dev/sdi1 on /media/GDMENU type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,showexec,utf8,flush,errors=remount-ro) <---this is the bind mounted path
```

**Comment by sonik-br** [comment]
My bad. It was missing a file.
Please try again with this new build 
[GDMENUCardManagerKDE2.zip](https://github.com/sonik-br/GDMENUCardManager/files/6501092/GDMENUCardManagerKDE2.zip)

Also, click on the info/about button. It will get some variables about the system and mount points. It should copy it to the clipboard and show the info on the screen.
Paste the info here. Take care to **remove any sensitive information** from it. You can remove the listed mount points and leave only the one for your SD Card.

**Comment by cinnamonmatexfce** [comment]
Fine! It worked! Thanks

P. S.: the info/about button shows up infos about the program itself, I don't see any other system's informations...

**Comment by sonik-br** [comment]
Yay!
I've put the info on the wrong button. :/
It's on the games list. The one to show info about each game.

**Comment by cinnamonmatexfce** [comment]
> Yay!
> I've put the info on the wrong button. :/
> It's on the games list. The one to show info about each game.

```
Linux 5.12.4-zen1-2-zen #1 ZEN SMP PREEMPT Sat, 15 May 2021 20:58:03 +0000
X64
X64
.NET Core 3.1.13
True
False
Listing mount points...
-----------------------------------
True	Ram	proc	/proc	/proc
-----------------------------------
True	Ram	sysfs	/sys	/sys
-----------------------------------
True	Ram	tmpfs	/dev	/dev
-----------------------------------
True	Ram	tmpfs	/run	/run
-----------------------------------
True	Unknown		/sys/firmware/efi/efivars	/sys/firmware/efi/efivars
-----------------------------------
True	Fixed	ext4	/	/
-----------------------------------
True	Ram	securityfs	/sys/kernel/security	/sys/kernel/security
-----------------------------------
True	Ram	tmpfs	/dev/shm	/dev/shm
-----------------------------------
True	Ram	devpts	/dev/pts	/dev/pts
-----------------------------------
True	Unknown		/sys/fs/cgroup	/sys/fs/cgroup
-----------------------------------
True	Fixed	pstorefs	/sys/fs/pstore	/sys/fs/pstore
-----------------------------------
True	Unknown		/sys/fs/bpf	/sys/fs/bpf
-----------------------------------
True	Ram	binfmt_misc	/proc/sys/fs/binfmt_misc	/proc/sys/fs/binfmt_misc
-----------------------------------
True	Ram	hugetlbfs	/dev/hugepages	/dev/hugepages
-----------------------------------
True	Ram	mqueue	/dev/mqueue	/dev/mqueue
-----------------------------------
True	Ram	debugfs	/sys/kernel/debug	/sys/kernel/debug
-----------------------------------
True	Unknown		/sys/kernel/tracing	/sys/kernel/tracing
-----------------------------------
True	Ram	binfmt_misc	/proc/sys/fs/binfmt_misc	/proc/sys/fs/binfmt_misc
-----------------------------------
True	Ram	configfs	/sys/kernel/config	/sys/kernel/config
-----------------------------------
True	Ram	fusectl	/sys/fs/fuse/connections	/sys/fs/fuse/connections
-----------------------------------
True	Ram	tmpfs	/tmp	/tmp
-----------------------------------
True	Fixed	ext4	/mnt/foo1	/mnt/foo1
-----------------------------------
True	Fixed	msdos	/efi	/efi
-----------------------------------
True	Network	fuse	/mnt/windowspartition	/mnt/windowspartition
-----------------------------------
True	Fixed	ext4	/mnt/raid0A	/mnt/raid0A
-----------------------------------
True	Fixed	ext4	/mnt/raid0B	/mnt/raid0B
-----------------------------------
True	Ram	tmpfs	/run/user/#userid#	/run/user/#userid#
-----------------------------------
True	Network	fuse	/run/user/#userid#/gvfs	/run/user/#userid#/gvfs
-----------------------------------
True	Fixed	msdos	/run/media/$USERNAME/GDEMU	/run/media/$USERNAME/GDEMU

```

**Comment by sonik-br** [comment]
Thanks.
I will merge the code and build a new version on the weekend.

**Comment by cinnamonmatexfce** [comment]
Thank you! 💪
