### ISSUE TITLE
7z: "Access denied" to "01" folder when "Save Changes"

### ISSUE THREAD

**Issue by cinnamonmatexfce** [sonik-br/GDMENUCardManager#8]
Implemented 7z and rar support for linux by using the SharpCompress lib.
@cinnamonmatexfce and @Mi1ezDR please go to the releases and grab the file named BETA.
It needs some testing. Let me know of any problem.

_Originally posted by @sonik-br in https://github.com/sonik-br/GDMENUCardManager/issues/2#issuecomment-844502753_

Adding 7z files to the list works, but when "Save Changes" it will stop with error "Access to the path `/run/media/$USERNAME/foo/01` is denied.", **note it's referring to `01` folder**!

![GDMENUCardManager v1 3 2-linux-x64-BETA  access denied](https://user-images.githubusercontent.com/65762930/119022055-75f79d80-b9a0-11eb-9ad9-8440a696897d.jpg)
![GDMENUCardManager v1 3 2-linux-x64-BETA  cannot load](https://user-images.githubusercontent.com/65762930/119022115-8576e680-b9a0-11eb-87ca-f47cac91d8ab.jpg)

**Comment by sonik-br** [comment]
01 folder is the menu folder. It need's to update the menu with the new game list.
Saving without adding a 7z file still works?
Try to just change the order of one game and save.

**Comment by sonik-br** [comment]
Hi @cinnamonmatexfce .
Can you do this test?

**Comment by cinnamonmatexfce** [comment]
Adding uncompressed `.gdi` games works and also works when sorting list.
Changes will be saved with no issues at all.
Tested with latest [BETA](https://github.com/sonik-br/GDMENUCardManager/releases/download/1.3.2/GDMENUCardManager.v1.3.2-linux-x64-BETA.tar.gz)

**Comment by sonik-br** [comment]
It's working fine on my Ubuntu on VM.
Just added some 7z and rar games to my card and it saved ok.

![image](https://user-images.githubusercontent.com/16923826/120106557-cf479580-c133-11eb-870b-eced94dfc424.png)

**Comment by sonik-br** [comment]
Closing as this seems to be fixed.
Feel free to open again if needed.
