### ISSUE TITLE
Not compatible with a custom GDEMU theme

### ISSUE THREAD

**Issue by PiKeyAr** [sonik-br/GDMENUCardManager#9]
Hello, this tool worked great for me until I tried a custom theme for GDEMU called "Cleancast v2 rev1 (Red Swirl)". I replaced `1ST_READ.BIN` in `tools\menu_data` and it built just fine, however the console hangs on the SEGA license screen. If I put the original `1ST_READ.BIN` back in, it works fine.
Here's the modified file with the custom theme:
[1ST_READ.zip](https://github.com/sonik-br/GDMENUCardManager/files/6603745/1ST_READ.zip)
The console booted fine with this file when I used the old GDEMU_SD tool instead, so I thought I should report this just in case.

**Comment by sonik-br** [comment]
Hi.
I think the problem is scrambled vs unscrambled binary file.
Try with an unscrambled file.

**Comment by PiKeyAr** [comment]
Thank you for your help. I tested with an unscrambled binary and it worked.
